using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace Problem2
{
    class Program
    {
        static void Main(string[] args)
        {
            /*
            Each new term in the Fibonacci sequence is generated by adding the previous two terms.
            By starting with 1 and 2, the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            By considering the terms in the Fibonacci sequence whose values do not exceed four million,
            find the sum of the even-valued terms.
            */

            int term1 = 1;
            int term2 = 2;
            List<int> fibTerms = new List<int>();
            fibTerms.Add(term1);
            fibTerms.Add(term2);
            int iteration = 0;
            int limitCheck = fibTerms[0];
            int limit = 4000000;
            while (limitCheck < limit) //4000000
            {
                limitCheck = fibTerms[iteration] + fibTerms[iteration + 1];
                fibTerms.Add(limitCheck);
                iteration++;
            }
            /*
            foreach (int item in fibTerms) //how me the terms are adding correctly
            {
                Console.WriteLine(item);
            }
            Console.ReadLine();
            */
            int answerSum = 0;
            foreach (int item in fibTerms)
            {
                if (item % 2 ==0)
                {
                    answerSum += item;
                }
            }
            Console.WriteLine("{0:N}",answerSum);
            Console.ReadLine();
        }
    }
}
